### ISSUE TITLE
jos ei vastauksia, piilota "quiz results"

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#13]
![image](https://user-images.githubusercontent.com/523235/67283175-d3cdb600-f4db-11e9-9f62-f7183346e30e.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/163cce69cf7a084b63f57bfd5ba146a5a5de23ee
