### ISSUE TITLE
näytä kaikissa tilanteissa myös tulevat, vielä aukeamattomat quizzit taulukossa

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#14]
nyt kun edes 1. ei ole auki, ei näy mitään:

![image](https://user-images.githubusercontent.com/523235/67525676-ddae0f80-f6bb-11e9-96db-8bc0c8c66eb6.png)

paremi olisi että määritellyt mutta vielä kiinni olevat näkyisvät samaan tyyliin kun ne näkyy jos eka quizz on auki

![image](https://user-images.githubusercontent.com/523235/67525531-9758b080-f6bb-11e9-91c3-8b43e68cd904.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/c1f225d17e387305d6723f5e80753100bba07d5c
