### ISSUE TITLE
viikoittaisten tehtävien määrä fucked up

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#15]
vaikka on 

![image](https://user-images.githubusercontent.com/523235/67596066-96ce2180-f770-11e9-846d-97df1a9004dd.png)

niin

![image](https://user-images.githubusercontent.com/523235/67596093-a51c3d80-f770-11e9-80f0-f485bacd760f.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/f9fa1517432d07a3249d2481c5e72b063ca0225d
