### ISSUE TITLE
Virhe submitin jälkeen

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#16]
![07E2DD42-5A9D-4818-A048-7124B4880409](https://user-images.githubusercontent.com/523235/67620697-47403200-f812-11e9-9efd-755e9a3c7ecd.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/6ec5f8b2da51d834d3b97c22ae7508168c9dc7ec
