### ISSUE TITLE
Move quiz deadline back to 23:59:59

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#17]
12:00 is deprecated

![image](https://user-images.githubusercontent.com/523235/67635188-b712f300-f8cc-11e9-9786-fc7e75805af6.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/5375898c505805320c57f50ea4212970ea8c234d
