### ISSUE TITLE
fukap: opiskelijan normilaskarit ei näy

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#18]
mutta

![image](https://user-images.githubusercontent.com/523235/67638658-b63f8880-f8ef-11e9-8608-f3e15e64a49f.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/29ce1d7f964edad552a599532aef594811074eb0
