### ISSUE TITLE
vastauksiin vaihtoehdot tosi [] eptosi [] 

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#19]
ts vaadi tekemään vastaus eksplisiittisesti, eli jos ei ole valinnut kumpaakaan, se ei tarkota samaa kuin false

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/04269d87279d55bb78c4d9678edf6ded5d99f59f
