### ISSUE TITLE
admin cli: mahdollisuus merkata opiskelijalle miniprojekti hyväksiluetuksi

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#20]
https://github.com/UniversityOfHelsinkiCS/coursestats/blob/master/admin.js#L374

toimiiko edelleen?

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/blob/327af24c1e865c6a48cc6c6e9a2b512e2dca5488/server/controllers/projectsController.js#L125 soon kälissä
