### ISSUE TITLE
submissio enabled vaikka ei mitään merkattu

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#23]
![image](https://user-images.githubusercontent.com/523235/67990988-52df8e80-fc40-11e9-9e2d-8dccbaac3e0c.png)

aiemmin vaadittiin että tunnit on laitettu ja github-kentässä jotain muuta kun esitäytetty kama

**Comment by Jakousa** [comment]
https://github.com/mluukkai/fsstats_fronentd/blob/master/src/components/SubmissionForm.js Alkuperäisessä ei painike ole koskaan disabled. Diffasin vielä tiedostot enkä löytänyt oikeastaan muita kuin lintterin tekemiä.

Nappulan disablointi on uusi feature, tehdäänkö? 

Painamalla painiketta täyttämättä kenttiä saat notifikaation kuten aiemminkin.
