### ISSUE TITLE
mallivastaukset

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#26]
aiemmin mallivastaukset oli laitettu bacendin repoon näin: 

![image](https://user-images.githubusercontent.com/523235/68429205-5762f480-01b6-11ea-90ed-3516abb7128d.png)

feature pitäisi saada tulille

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/351f425bf3dc133d86ecfc40dca6b8183508e8d1
