### ISSUE TITLE
admin sivulle tieto onko miniproj hyväksiluettu / onko jossain ryhmässä

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#27]
yksi sarake lisää, sarakkeessa vaikka
- H (=hyväksiluettu)
- R (=ryhmässä) 

tms

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/3bd8607a8c5070eafe2899991800dfbc47975b32
