### ISSUE TITLE
opiskelijan _my submissions_ -sivulle tieto kunkin osan quizzien pistemäärästä

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#3]
esim yksirivinen taulukko, missä oikein/kaikki per osa

**Comment by Jakousa** [comment]
simple https://github.com/UniversityOfHelsinkiCS/coursestats/commit/e9fbcae7750328b6fe1aa33ade8cc9ea348b19fa
