### ISSUE TITLE
endpoint, joka näyttää kaikkien miniprojektien githubrepot satunnaisessa järjestyksessä

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#33]
samaan tapaan kun softan vanha versio

![image](https://user-images.githubusercontent.com/523235/69749019-47558980-1152-11ea-9db5-fc633cd7ab19.png)

**Comment by Jakousa** [comment]
https://study.cs.helsinki.fi/stats/api/courses/ohtu2019/projects/repositories
