### ISSUE TITLE
Total Points / Score for "Quiz results" -table

### ISSUE THREAD

**Issue by mitami** [UniversityOfHelsinkiCS/coursestats#34]
Quiz results -taulukon pohjimmaiseksi riviksi yhteenlasketut oikeat vastaukset ja kaikkien kysymysten kokonaismäärä, sekä "score", jossa score on score -kolumnin yhteenlasketut pisteet.

Esimerkki:

| Part | Right answers | Score |
| --- | --- | --- |
| 1 | 30 / 60 | 0.5 |
| 2 | 60 / 60 | 1 |
| total | 90 / 120 | 1.5 / 2 |

**Comment by Jakousa** [comment]
Right answers kolumnille piti tehdä muutos. Laitetaan esim "Missed: 30". Perusteena tähän että loppupisteet ovat erillisten osien summa - ei välttämättä suoraan saatavilla oikeista vastauksista.
