### ISSUE TITLE
Käyttäjä voi täyttää vertaispalautteen niin että osa kohdista on tyhjiä.

### ISSUE THREAD

**Issue by rovaniemi** [UniversityOfHelsinkiCS/coursestats#35]
![Screenshot 2019-12-22 at 16 40 26](https://user-images.githubusercontent.com/21308995/71323249-ca5fca80-24d9-11ea-8e77-ab5fdf9078c8.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/97d5bbf4e2b9c290f670200307a240a2b5610b6b
