### ISSUE TITLE
admin-näkymä *eitoimi*

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#36]
fullstackissä ei submissioita, mutta ohtun data samassa listassa

https://study.cs.helsinki.fi/stats/courses/fullstack2020/admin

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/430fb7389960006dcecbd94ee3a300099df6dea3
