### ISSUE TITLE
jokin tapa määritellä quiz.json:iin mitkä quizit ovat vastattavissa

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#4]
ts jsonissa pitäisi voida olla keskeneräisiä quizzeja joita ei tule vielä näyttää

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/2b3bfd9156609d7affbe1b194e215c538f774e38
