### ISSUE TITLE
quizz points fak'd up

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#41]
ks https://study.cs.helsinki.fi/stats/courses/ohtu-avoin-2020/admin
ja https://study.cs.helsinki.fi/stats/courses/ohtu2019/admin

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/84b8705a08578dd10fb23284ce0634dbd3a9dad7
