### ISSUE TITLE
quiz sivun reloadauksen heisenbug

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#6]
kun reloadailin sivua https://study.cs.helsinki.fi/courses/courses/ohtu2019/quiz/1 monta (=reilusti yli 10) kertaa peräkkäin, seuraava virhe toistui aina välillä 

![image](https://user-images.githubusercontent.com/523235/67164039-e1215e00-f37e-11e9-9071-ab96cb380839.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/9443f2d3e324aaaed880a56459d716f92172e87d
