### ISSUE TITLE
opiskelijan näkymä admineille

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#8]
kun opiskelijaa klikkaamalla simppeli näkymä opiskelijan vastauksiin

![image](https://user-images.githubusercontent.com/523235/67191978-5763a600-f3fb-11e9-8c45-5eb0e809a2e5.png)

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/e0623103817297634a6213f5edeccda5955942f0
