### ISSUE TITLE
quizzin vastausten välitalletus

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/coursestats#9]
eli mahollisuus opiskelijalle tehdä quizzit osittain ja submitata vasta myöhempänä ajankohtana

**Comment by Jakousa** [comment]
kaikki mitkä toimii on fine. voishan olla että synkattas backiin jokaisella rastin laittamisella

**Comment by Jakousa** [comment]
https://github.com/UniversityOfHelsinkiCS/coursestats/commit/501f4911d9dd5d6299718c045c0c301b9f093b36
